### ISSUE TITLE
Landing Page UI

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/ResourceProjects.org#13]
We need a bunch of UI improvements for the landing page.

- [ ] a module (series of modules) for latest additions (see #10) 
- [ ] a set of aggregate summary stats for data contained (see #9) 
- [ ] modified landing text (see #8)
